### PR TITLE
Setup

### PR DESCRIPTION
**Pull request by abdullah-cyber**
This PR:
-Understand how to parse a Figma design to create a UI.
-Flexbox to place elements in the page.
-Build a personal portfolio site.
-Use images and backgrounds to enhance the look of the website.

### CODE REVIEW

**Comment by was-coder** [comment]
### This is good overall, nice job but let's correct all the following:

image

The logo should be enclosed with an `a` tag
The hamburger should also be enclosed inside a `nav` tag

**Comment by was-coder** [comment]
You are only asked to create the setup milestone, the medium and desktop version you did for it is not required for this particular milestone. Remove those versions and just make it as it was stated in the milestone

As you progress you will be working on other screen sizes

**Comment by was-coder** [comment]
image

The `main` tag should be a `section tag`
The text should be an `h1` tag instead of an `h3` tag

**Comment by was-coder** [comment]
image

The let's connect text should be enclosed with an `a` tag

The list of icons should use a `ul` tag to group them, and `li` per icon with each icon having an `a` tag

**Comment by was-coder** [comment]
image

image

You can `flex` the _flex-container_ div instead of writing that much code by flexing the right and left separately... Just a suggestion to reduce code

**Comment by was-coder** [comment]
image

There is a term called [Dry](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself), You have many repetition of the `width : auto`, you can group them all in one form. example:

`body,
html,
.my-main {
width:auto;}`

Do the same for any other repetition you have, just like the font-family: poppins

**Comment by was-coder** [comment]
Make your README file to be more descriptive, use [this](https://github.com/was-coder/professional-portfolio#readme) as a reference

**Comment by dollarrr** [comment]
this is a modified code for the setup 
a review was made on it and it has been updated

**Pull request merged**
